# Generated by Django 5.1.6 on 2025-03-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordertype',
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
