# Generated by Django 5.1.6 on 2025-03-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.users', verbose_name='user')),
            ],
        ),
    ]